# 100 numpy exercises

#### 1. Import the numpy package under the name `np`(★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)


In [ ]:
#print Numpy version
print("NumPy version:", np.version)  #Displaysversion of the installed numpy pacage

#print Numpy configuration
np.show_config() #Displays configuration details

NumPy version: <module 'numpy.version' from 'c:\\Users\\MINE\\anaconda3\\envs\\arewads\\lib\\site-packages\\numpy\\version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/MINE/anaconda3/envs/arewads/Library/include
    lib directory: C:/Users/MINE/anaconda3/envs/arewads/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_0123vcxhf8\croot\numpy_and_numpy_base_1725470331966\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/MINE/anaconda3/envs/arewads/Library/include
    lib directory: C:/Users/MINE/anaconda3/envs/arewads/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_0123vcxhf8\croot\numpy_and_numpy_base_1725470331966\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
   

#### 3. Create a null vector of size 10 (★☆☆)


In [6]:
null_vector=np.zeros(10)
print("Null vector of size 10:", null_vector)

Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [7]:
#create an array
arr=np.zeros(10)

#Get the memory size
memory_size=arr.nbytes
print(f"Memory size of the array:, {memory_size} bytes")

Memory size of the array:, 80 bytes


In [8]:
arr.size*arr.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [10]:
#create a null vector of size 10
vector=np.zeros(10)

# set the fifth element (index 4) to 1
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [12]:
# create a vector with values from 10 to 49
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [13]:
# reverse vector 
reversed_vector=vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
#create a 3x3 matrix with value from 0 to 8
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr)

print(indices[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
# Create a 3x3 identity matrix 
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
random_array=np.random.random((3,3,3))
random_array

array([[[0.59562096, 0.54003493, 0.67519453],
        [0.58236148, 0.38592748, 0.45721954],
        [0.43627519, 0.11312016, 0.40905859]],

       [[0.01448611, 0.70586977, 0.8215701 ],
        [0.90034266, 0.4929213 , 0.13711255],
        [0.14849068, 0.36291511, 0.57178062]],

       [[0.08596971, 0.62532644, 0.05357819],
        [0.32349328, 0.515001  , 0.22983041],
        [0.06685098, 0.00742902, 0.40050091]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [23]:
# create a 10x10  array with random values between 0 and 1
array=np.random.random((10,10))

# Find the minimum and maximum values
min_val=array.min()
max_val=array.max()

print("10x10 Random Array:/n",array)
print("/nMinimum Value:", min_val)
print("/nMaximum:" ,max_val)

10x10 Random Array:/n [[0.83657242 0.65078684 0.97644508 0.16208057 0.65215753 0.7506687
  0.76484544 0.81318576 0.28205791 0.43692242]
 [0.78007585 0.39966614 0.04351495 0.39874725 0.05217427 0.17491387
  0.86176255 0.2062847  0.58292705 0.90471275]
 [0.51069269 0.76636824 0.7207454  0.07151818 0.20765235 0.82423795
  0.46852531 0.94593149 0.57921849 0.41784236]
 [0.96706371 0.16664306 0.41383444 0.72622141 0.63421954 0.48420481
  0.28003344 0.89497529 0.73118728 0.9011527 ]
 [0.14225477 0.55003248 0.59051454 0.54420784 0.17398126 0.77996338
  0.06294559 0.40305865 0.97489789 0.85317616]
 [0.4394919  0.25978699 0.97098414 0.4781055  0.04889584 0.01573089
  0.9795935  0.86735314 0.28163265 0.31031015]
 [0.31250477 0.79963105 0.67933898 0.67025497 0.8350864  0.72719634
  0.14319358 0.37607457 0.57305988 0.85943075]
 [0.05473068 0.09310648 0.89033094 0.20845491 0.89884022 0.52365849
  0.64131748 0.87094404 0.00428586 0.62640582]
 [0.60871005 0.91570225 0.94596988 0.18865477 0.91330872 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [24]:
random_vect=np.random.rand(30)
mean_value=vector.mean()
print("Random Vector:\n", vector)
print("\nMean Vector:", mean_value)

Random Vector:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Mean Vector: 29.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
array_2d=np.ones((5,5)) #create a 5x5 array of ones
array_2d[1:-1, 1:-1]=0 # set inner element to zero
print("2D Array with Border 1s and inside 0s:\n", array_2d)

2D Array with Border 1s and inside 0s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [27]:
original_array=np.ones((5,5))

border_array=np.pad(original_array, pad_width=1, mode='constant',
                    constant_values=0)
print("Original Array:\n",original_array)
print("\nArray with Border of 0's:\n", border_array)

Original Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array with Border of 0's:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
## result of the following expression
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
matrix=np.diag([1,2,3,4], k=-1)
print("Matrix With value below diagonal:\n", matrix)

Matrix With value below diagonal:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
checkerboard=np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2]=1
checkerboard[::2, 1::2]
print("Checkerboard pattern:\n",checkerboard)

Checkerboard pattern:
 [[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
array=np.zeros((6,7,8))
index=np.unravel_index(100, array.shape)
print("Index of 100th element:",index)

Index of 100th element: (np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
pattern=np.array([[0,1],[1,0]])
checkerboard_tile=np.tile(pattern,(4,4))
print("checkerboard using tile:\n", checkerboard_tile)

checkerboard using tile:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [36]:
random_matrix=np.random.rand(5,5)
normalized=(random_matrix-np.min(random_matrix))/(np.max(random_matrix)-np.min(random_matrix))
print("Normalized matrix:\n", normalized)


Normalized matrix:
 [[0.99212618 0.67236925 0.29534704 0.3262724  0.621775  ]
 [0.89725495 0.14249224 0.59282734 0.4381219  0.        ]
 [0.4541723  0.13333952 0.1828922  0.43117611 0.87735303]
 [0.47206026 0.95113867 0.99511711 0.68844177 1.        ]
 [0.28199156 0.53374934 0.25362076 0.31719897 0.83235098]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [38]:
rgba_dtype=np.dtype([('r', np.ubyte), ('g', np.ubyte),('b',np.ubyte), ('a',np.ubyte)])
color=np.array((255,0,0,255),dtype=rgba_dtype)
print("Custom RGBA dtype:\n", color)

Custom RGBA dtype:
 (255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
A=np.random.rand(5,3)
B=np.random.rand(3,2)
product=np.dot(A,B)
print("Product of 5x3 and 3x2 matrix:\n", product)

Product of 5x3 and 3x2 matrix:
 [[0.56218481 0.66897007]
 [1.04608062 0.84071092]
 [0.62257424 0.75008163]
 [1.03879152 1.23907741]
 [0.78977087 0.90585078]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
arr=np.arange(11)
arr[(arr > 3)& (arr <8)] *=-1
print("Modified array:\n", arr)

Modified array:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [43]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


C:\Users\MINE\AppData\Local\Temp\ipykernel_19888\1729466501.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\MINE\AppData\Local\Temp\ipykernel_19888\1729466501.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\MINE\AppData\Local\Temp\ipykernel_19888\1729466501.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [45]:
Z=np.array([1.2, -1.7, 2.5, -2.3])
rounded=np.copysign(np.ceil(np.abs(Z)),Z)
print(rounded)

[ 2. -2.  3. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [46]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
common_val=np.intersect1d(a,b)
print(common_val)

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [64]:
import warnings

#ignore all warnings
warnings.filterwarnings('ignore')
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [49]:
np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [ ]:
print(np.sqrt(-1)) #nan
print(np.emath.sqrt(-1))  #ij
print(np.sqrt(-1)==np.emath.sqrt(-1))  #false

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)



In [53]:
import datetime
today=np.datetime64('today' , 'D')
yesterday=today - np.timedelta64(1, 'D')
tomorrow=today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-06-25
Today: 2025-06-26
Tomorrow: 2025-06-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
july_2016=np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.ones(3)
B=np.ones(3)*2

# In-place computation
A+=B          # A =A + B
A*= -0.5       # A = A* (-A/2)
print(A)


[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [57]:
Z=np.random.uniform(0,10,5)

print("Original:", Z)
print("Method 1:", Z.astype(int))
print("Method 2:", np,floor(Z))
print("Method 3:", np.trunc(Z))
print("Method 4:", np.fix(Z))

Original: [6.55623158 8.94041683 5.04549712 7.43883273 7.12779521]
Method 1: [6 8 5 7 7]
Method 2: <module 'numpy' from 'c:\\Users\\MINE\\anaconda3\\envs\\arewads\\lib\\site-packages\\numpy\\__init__.py'> [6. 8. 5. 7. 7.]
Method 3: [6. 8. 5. 7. 7.]
Method 4: [6. 8. 5. 7. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [58]:
Z=np.zeros((5,5))
Z +=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [60]:
def generate():
    for i in range(10):
        yield i

    Z=np.fromiter(generate(), dtype=int)
    print(Z)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [62]:
Z=np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z=np.random.rand(10)
Z.sort()   #sort in ascending order
Z

array([0.09366044, 0.11794672, 0.15948991, 0.17976846, 0.23664425,
       0.32377263, 0.40162397, 0.73350119, 0.83922317, 0.91212836])